### ISSUE TITLE
TO-DO LIST

### ISSUE THREAD

**Issue by Deppu** [Deppu/class-data-project#1]
- [ ] Statistik intrinsic setiap kelas

- [ ] Pengurutan kelas sesuai permintaan

- [ ] Pencarian nama/nim mahasiswa

- [ ] Pencarian kelas dengan nilai tertinggi/terendah

- [ ] Penyimpanan data

- [ ] Memuat data (optional)
